# Generated by Django 5.2.4 on 2025-07-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employee_task_assign_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assign_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
    ]
